name: GitHub CI

on:
  push:
    branches: [ "master" ]
    tags:
      - '**'
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  linux32_build:
    name: Linux x86 Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release
      - name: Package
        run: tar czf warp_minio_server_linux32.tar.gz -C target/release warp_minio_server
        if: ${{ github.event_name != 'pull_request' }}
      - name: Upload Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: warp_minio_server_linux32.tar.gz
          path: warp_minio_server_linux32.tar.gz
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
        with:
          files: warp_minio_server_linux32.tar.gz
          draft: true

  aarch64_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: aarch64-unknown-linux-gnu
      - name: Install cross-compile tools
        run: sudo apt-get update && sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
      - name: Compile OpenSSL for ARM64
        run: |
          export CC=aarch64-linux-gnu-gcc
          wget https://www.openssl.org/source/openssl-3.2.0.tar.gz
          tar xzf openssl-3.2.0.tar.gz
          cd openssl-3.2.0
          ./Configure linux-aarch64  no-shared --prefix=/usr/local/aarch64
          make
          sudo make install
      - name: Configure build environment
        run: |
          echo "RUSTFLAGS=-C linker=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
      - name: Set environment variables for OpenSSL
        run: |
          echo "OPENSSL_DIR=/usr/local/aarch64" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/usr/local/aarch64/lib" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/local/aarch64/include" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=/usr/local/aarch64/lib/pkgconfig" >> $GITHUB_ENV
      - name: Build for ARM64
        run: cargo build --release --target aarch64-unknown-linux-gnu
      - name: Package ARM64 build
        if: ${{ github.event_name != 'pull_request' }}
        run: tar czf warp_minio_server_arm64.tar.gz -C target/aarch64-unknown-linux-gnu/release warp_minio_server
      - name: Upload Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: warp_minio_server_arm64.tar.gz
          path: warp_minio_server_arm64.tar.gz
      - name: Draft Release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
        with:
          files: warp_minio_server_linux32.tar.gz
          draft: true

  windows64_build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build for Windows x64
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Package Windows x64
        if: ${{ github.event_name != 'pull_request' }}
        run: Compress-Archive -Path target\x86_64-pc-windows-msvc\release\*.exe -DestinationPath warp_minio_server_windows_x64.zip
      - name: Upload Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: warp_minio_server_windows_x64.zip
          path: warp_minio_server_windows_x64.zip
      - name: Upload Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v3
        with:
          name: warp_minio_server_windows_x64.zip
          path: warp_minio_server_windows_x64.zip
      - name: Draft Release
        if: ${{ github.event_name != 'pull_request' && startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v1
        with:
          files: warp_minio_server_windows_x64.zip
          draft: true